// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCedjLmZFOaflOZHGlfuiUzGV0IDlEtz0o',
    appId: '1:707113873023:web:783bb1a7453fb46daed94a',
    messagingSenderId: '707113873023',
    projectId: 'e-commerce-1c5f4',
    authDomain: 'e-commerce-1c5f4.firebaseapp.com',
    storageBucket: 'e-commerce-1c5f4.appspot.com',
    measurementId: 'G-GGDNEDMTH4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb3-DYTIiLLT-jlvNOCQi74Ff8rNrPPAI',
    appId: '1:707113873023:android:b432f26ef88c2d64aed94a',
    messagingSenderId: '707113873023',
    projectId: 'e-commerce-1c5f4',
    storageBucket: 'e-commerce-1c5f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsxJUFuiQZ6-MI5TQRnB5p7GRJ3Nwu0jE',
    appId: '1:707113873023:ios:676168bbeed57f96aed94a',
    messagingSenderId: '707113873023',
    projectId: 'e-commerce-1c5f4',
    storageBucket: 'e-commerce-1c5f4.appspot.com',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsxJUFuiQZ6-MI5TQRnB5p7GRJ3Nwu0jE',
    appId: '1:707113873023:ios:676168bbeed57f96aed94a',
    messagingSenderId: '707113873023',
    projectId: 'e-commerce-1c5f4',
    storageBucket: 'e-commerce-1c5f4.appspot.com',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCedjLmZFOaflOZHGlfuiUzGV0IDlEtz0o',
    appId: '1:707113873023:web:b86dba686def684eaed94a',
    messagingSenderId: '707113873023',
    projectId: 'e-commerce-1c5f4',
    authDomain: 'e-commerce-1c5f4.firebaseapp.com',
    storageBucket: 'e-commerce-1c5f4.appspot.com',
    measurementId: 'G-L3PVK0Q4VX',
  );
}
